[vscode]
base_url = "https://code.visualstudio.com/sha/download"
build = "stable"
[vscode.os]
windows = ["win32-x64-user", "win32-arm64-user"]
macos = ["darwin-arm64", "darwin-universal"]
linux = ["linux-deb-x64", "linux-deb-arm64", "linux-rpm-arm64", "linux-rpm-x64"]


[firefox]
base_url = "https://download.mozilla.org/"
product = "firefox-latest-ssl"
lang="zh-CN"
[firefox.os]
macos = ["osx", ]
windows = ["win64", "win64-aarch64"]

[github-desktop]
base_url = "https://central.github.com/deployments/desktop/desktop/latest/"
download_url = ["darwin", "darwin-arm64", "win32"]
[git]
base_url = "https://git-scm.com/download/win"
xpath = ['//*[@id="main"]/p[2]/strong/a', '//*[@id="main"]/p[3]/strong/a']

[obs]
base_url = "https://obsproject.com"
xpath = ['//*[@id="home_downloads"]/a[1]', '//*[@id="mac_extra"]/a[2]', '//*[@id="mac_extra"]/a[3]']
