[vscode]
base_url = "https://code.visualstudio.com/sha/download?build=stable"
[vscode.os]
[[vscode.os.windows]]
os = "win32-x64-user"
[[vscode.os.windows]]
os = "win32-arm64-user"

[[vscode.os.macos]]
os = "darwin-arm64"

[[vscode.os.macos]]
os = "darwin-universal"

[[vscode.os.linux]]
os = "linux-deb-x64"

[[vscode.os.linux]]
os = "linux-deb-arm64"

[[vscode.os.linux]]
os = "linux-rpm-x64"

[[vscode.os.linux]]
os = "linux-rpm-arm64"


[firefox]
base_url = "https://download.mozilla.org/"
product = "firefox-latest-ssl"
lang = "zh-CN"
[firefox.os]
macos = ["osx", ]
windows = ["win64", "win64-aarch64"]

[github-desktop]
base_url = "https://central.github.com/deployments/desktop/desktop/latest/"
download_url = ["darwin", "darwin-arm64", "win32"]
[git]
base_url = "https://git-scm.com/download/win"
xpath = ['//*[@id="main"]/p[2]/strong/a', '//*[@id="main"]/p[3]/strong/a']

[obs]
base_url = "https://obsproject.com"
xpath = ['//*[@id="home_downloads"]/a[1]', '//*[@id="mac_extra"]/a[2]', '//*[@id="mac_extra"]/a[3]']

[postman]
base_url = "https://dl.pstmn.io/download/latest"
download_url = ["osx_64", "osx_arm64", "win64", "linux_64", "linux_arm64"]

[docker]
base_url = "https://desktop.docker.com"
download_url = [
    "mac/main/amd64/Docker.dmg",
    "mac/main/arm64/Docker.dmg",
    "win/main/amd64/Docker%20Desktop%20Installer.exe"

]
